<a href="https://colab.research.google.com/github/Kamruzzaman2200/Ai/blob/main/Heart_Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")


In [11]:
df = pd.read_csv('/content/drive/MyDrive/Heart disease/heart_disease.csv')

In [12]:
df.head()

Age  Gender  Blood Pressure  Cholesterol Level Exercise Habits Smoking  \
0  56.0    Male           153.0              155.0            High     Yes   
1  69.0  Female           146.0              286.0            High      No   
2  46.0    Male           126.0              216.0             Low      No   
3  32.0  Female           122.0              293.0            High     Yes   
4  60.0    Male           166.0              242.0             Low     Yes   

  Family Heart Disease Diabetes        BMI High Blood Pressure  ...  \
0                  Yes       No  24.991591                 Yes  ...   
1                  Yes      Yes  25.221799                  No  ...   
2                   No       No  29.855447                  No  ...   
3                  Yes       No  24.130477                 Yes  ...   
4                  Yes      Yes  20.486289                 Yes  ...   

  High LDL Cholesterol Alcohol Consumption Stress Level Sleep Hours  \
0                   No                High       Medium    7.633228   
1                   No              Medium         High    8.744034   
2                  Yes                 Low          Low    4.440440   
3                  Yes                 Low         High    5.249405   
4                   No                 Low         High    7.030971   

   Sugar Consumption Triglyceride Level  Fasting Blood Sugar  CRP Level  \
0             Medium              342.0                  NaN  12.969246   
1             Medium              133.0                157.0   9.355389   
2                Low              393.0                 92.0  12.709873   
3               High              293.0                 94.0  12.509046   
4               High              263.0                154.0  10.381259   

   Homocysteine Level  Heart Disease Status  
0           12.387250                    No  
1           19.298875                    No  
2           11.230926                    No  
3            5.961958                    No  
4            8.153887                    No  

[5 rows x 21 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object 
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object 
 5   Smoking               9975 non-null   object 
 6   Family Heart Disease  9979 non-null   object 
 7   Diabetes              9970 non-null   object 
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object 
 10  Low HDL Cholesterol   9975 non-null   object 
 11  High LDL Cholesterol  9974 non-null   object 
 12  Alcohol Consumption   7414 non-null   object 
 13  Stress Level          9978 non-null   object 
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption   

In [14]:
df.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

#Handeling null Values

In [15]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

In [16]:
le = LabelEncoder()
for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

#Split dataset

In [17]:
X = df.drop('Heart Disease Status', axis=1)
y = df['Heart Disease Status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Normalize features

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

# Initialize and train the Logistic Regression model
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:\n", report)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.8065
Classification Report:
               precision    recall  f1-score   support

           0       0.81      1.00      0.89      1613
           1       0.00      0.00      0.00       387

    accuracy                           0.81      2000
   macro avg       0.40      0.50      0.45      2000
weighted avg       0.65      0.81      0.72      2000

Confusion Matrix:
 [[1613    0]
 [ 387    0]]


#Naive Bayes

In [20]:
from sklearn.naive_bayes import GaussianNB

# Initialize and train the Naive Bayes model
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)

# Make predictions
y_pred_nb = model_nb.predict(X_test)

# Evaluate the model
accuracy_nb = accuracy_score(y_test, y_pred_nb)
report_nb = classification_report(y_test, y_pred_nb)
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)

print(f"Accuracy (Naive Bayes): {accuracy_nb}")
print("Classification Report (Naive Bayes):\n", report_nb)
print("Confusion Matrix (Naive Bayes):\n", conf_matrix_nb)

Accuracy (Naive Bayes): 0.8065
Classification Report (Naive Bayes):
               precision    recall  f1-score   support

           0       0.81      1.00      0.89      1613
           1       0.00      0.00      0.00       387

    accuracy                           0.81      2000
   macro avg       0.40      0.50      0.45      2000
weighted avg       0.65      0.81      0.72      2000

Confusion Matrix (Naive Bayes):
 [[1613    0]
 [ 387    0]]


#Support Vector Machine

In [21]:
from sklearn.svm import SVC

# Initialize and train the Support Vector Machine model
model_svm = SVC(random_state=42)
model_svm.fit(X_train, y_train)

# Make predictions
y_pred_svm = model_svm.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
report_svm = classification_report(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

print(f"Accuracy (SVM): {accuracy_svm}")
print("Classification Report (SVM):\n", report_svm)
print("Confusion Matrix (SVM):\n", conf_matrix_svm)

Accuracy (SVM): 0.8065
Classification Report (SVM):
               precision    recall  f1-score   support

           0       0.81      1.00      0.89      1613
           1       0.00      0.00      0.00       387

    accuracy                           0.81      2000
   macro avg       0.40      0.50      0.45      2000
weighted avg       0.65      0.81      0.72      2000

Confusion Matrix (SVM):
 [[1613    0]
 [ 387    0]]


#K-Nearest Neighbors



In [22]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize and train the K-Nearest Neighbors model
# You might want to experiment with different values for n_neighbors
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

# Make predictions
y_pred_knn = model_knn.predict(X_test)

# Evaluate the model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
report_knn = classification_report(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

print(f"Accuracy (KNN): {accuracy_knn}")
print("Classification Report (KNN):\n", report_knn)
print("Confusion Matrix (KNN):\n", conf_matrix_knn)

Accuracy (KNN): 0.7685
Classification Report (KNN):
               precision    recall  f1-score   support

           0       0.81      0.94      0.87      1613
           1       0.17      0.05      0.08       387

    accuracy                           0.77      2000
   macro avg       0.49      0.50      0.47      2000
weighted avg       0.68      0.77      0.72      2000

Confusion Matrix (KNN):
 [[1517   96]
 [ 367   20]]


# Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier

# Initialize and train the Decision Tree model
model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)

# Make predictions
y_pred_dt = model_dt.predict(X_test)

# Evaluate the model
accuracy_dt = accuracy_score(y_test, y_pred_dt)
report_dt = classification_report(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)

print(f"Accuracy (Decision Tree): {accuracy_dt}")
print("Classification Report (Decision Tree):\n", report_dt)
print("Confusion Matrix (Decision Tree):\n", conf_matrix_dt)

Accuracy (Decision Tree): 0.6645
Classification Report (Decision Tree):
               precision    recall  f1-score   support

           0       0.81      0.77      0.79      1613
           1       0.20      0.24      0.21       387

    accuracy                           0.66      2000
   macro avg       0.50      0.50      0.50      2000
weighted avg       0.69      0.66      0.68      2000

Confusion Matrix (Decision Tree):
 [[1238  375]
 [ 296   91]]


#Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest model
model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)

# Make predictions
y_pred_rf = model_rf.predict(X_test)

# Evaluate the model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
report_rf = classification_report(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

print(f"Accuracy (Random Forest): {accuracy_rf}")
print("Classification Report (Random Forest):\n", report_rf)
print("Confusion Matrix (Random Forest):\n", conf_matrix_rf)

Accuracy (Random Forest): 0.8065
Classification Report (Random Forest):
               precision    recall  f1-score   support

           0       0.81      1.00      0.89      1613
           1       0.00      0.00      0.00       387

    accuracy                           0.81      2000
   macro avg       0.40      0.50      0.45      2000
weighted avg       0.65      0.81      0.72      2000

Confusion Matrix (Random Forest):
 [[1613    0]
 [ 387    0]]


#Gradient Boosting

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

# Initialize and train the Gradient Boosting model
model_gb = GradientBoostingClassifier(random_state=42)
model_gb.fit(X_train, y_train)

# Make predictions
y_pred_gb = model_gb.predict(X_test)

# Evaluate the model
accuracy_gb = accuracy_score(y_test, y_pred_gb)
report_gb = classification_report(y_test, y_pred_gb)
conf_matrix_gb = confusion_matrix(y_test, y_pred_gb)

print(f"Accuracy (Gradient Boosting): {accuracy_gb}")
print("Classification Report (Gradient Boosting):\n", report_gb)
print("Confusion Matrix (Gradient Boosting):\n", conf_matrix_gb)

Accuracy (Gradient Boosting): 0.807
Classification Report (Gradient Boosting):
               precision    recall  f1-score   support

           0       0.81      1.00      0.89      1613
           1       1.00      0.00      0.01       387

    accuracy                           0.81      2000
   macro avg       0.90      0.50      0.45      2000
weighted avg       0.84      0.81      0.72      2000

Confusion Matrix (Gradient Boosting):
 [[1613    0]
 [ 386    1]]
